/**
 * Proving a player controls the address they claim — the interim copy.
 *
 * **This file is scheduled for deletion.** `kei-transaction` PR #142 lands
 * `wallet.signOwnershipChallenge()` and `verifyOwnershipProof()` in the SDK, for
 * exactly this purpose, and this module is that PR's shape written out here so
 * Button can have the boundary before the SDK ships it. When a published SDK
 * exports them, `src/ownership.ts` prefers the SDK's signer at runtime with no
 * code change, and the rest of this file is replaced by an import.
 *
 * The shape is copied deliberately, field for field:
 *
 *   const proof = await signOwnershipChallenge({ domain, address, nonce, context })
 *   // → { address, signature, challenge }
 *   const ok = await verifyOwnershipProof(proof, { domain, address, nonce, context, nonces })
 *
 * Two properties are the whole point, and both are asserted in
 * `test/ownership.test.ts` against the real hasher rather than against this
 * comment.
 *
 * **The digest is domain separated from a block.** A block hashes under
 * `blake2b-256("kei-block-v1")` (32 raw bytes) or, where the node has no layout
 * for it, under the ASCII `kei-block-local-v0`. A challenge hashes under the
 * ASCII `kei-ownership-challenge-v1`. Three prefixes that cannot be each other,
 * so a signature harvested here never authorises a send.
 *
 * **The caller's own `domain` travels inside the signed JSON, not as the byte
 * prefix.** That is PR #142's one deviation from Button's earlier draft and it
 * is strictly stronger: no string a caller picks can move the leading bytes of
 * the preimage towards a block's. The domain is still fully signed, so a proof
 * for one game does not verify for another.
 */

import { blake2b, bytesToHex, canonicalJson, publicKeyFromAddress, signHash, utf8, verifyHash } from '@keicoin/core'

/** The fixed bytes every ownership digest begins with. Never caller-supplied. */
export const OWNERSHIP_DOMAIN = 'kei-ownership-challenge-v1\n'

export const MAX_CHALLENGE_DOMAIN = 128
export const MAX_CHALLENGE_CONTEXT_ENTRIES = 16
export const MAX_CHALLENGE_CONTEXT_KEY = 64
export const MAX_CHALLENGE_CONTEXT_VALUE = 256

export type ChallengeContextValue = string | number | boolean

export interface OwnershipChallenge {
  /** The asking server's namespace, versioned by whoever picks it. */
  domain: string
  /** The address being proven. A wallet signs only for its own. */
  address: string
  /** Generated by whoever is asking, and checked by whoever is asking. */
  nonce: string
  /** Anything else the two sides must agree on. Bounded, and all of it signed. */
  context?: Readonly<Record<string, ChallengeContextValue>>
}

/**
 * What a server sends a client. `hash` is a courtesy — the digest the server
 * computed — and the wallet compares it against its own derivation rather than
 * signing it. A server that could name the bytes a wallet signs would be a
 * signing oracle, and the bytes a hostile one would pick are a send's hash.
 */
export interface OwnershipChallengeMessage extends OwnershipChallenge {
  hash?: string
}

export interface OwnershipProof {
  address: string
  signature: string
  challenge: OwnershipChallenge
}

/** A one-use record of nonces. `use` is a single claim, not a check then a mark. */
export interface NonceStore {
  /** True the first time this nonce is presented, false every time after. */
  use(nonce: string): boolean
}

export interface OwnershipExpectation extends OwnershipChallenge {
  nonces?: NonceStore
}

export class OwnershipError extends Error {}

/** The digest a proof signs. Deterministic: `canonicalJson` sorts keys. */
export function ownershipChallengeHash(challenge: OwnershipChallenge): string {
  return bytesToHex(blake2b(utf8(OWNERSHIP_DOMAIN + canonicalJson(normalise(challenge))), 32)).toUpperCase()
}

/** 256 bits from the platform CSPRNG, hex. One challenge, one nonce. */
export function randomChallengeNonce(): string {
  const bytes = new Uint8Array(32)
  crypto.getRandomValues(bytes)
  return bytesToHex(bytes).toUpperCase()
}

/**
 * Read a challenge off the wire.
 *
 * Everything a caller could send is refused here rather than downstream, and a
 * `hash` that disagrees with the derivation is an error rather than something
 * quietly corrected — the disagreement is the attack.
 */
export function parseOwnershipChallenge(message: unknown): OwnershipChallenge {
  const record = plainObject(message, 'challenge')

  const domain = text(record['domain'], 'domain', MAX_CHALLENGE_DOMAIN)
  const address = text(record['address'], 'address', 128)
  const nonce = text(record['nonce'], 'nonce', 128)

  const challenge: OwnershipChallenge = {
    domain,
    address,
    nonce,
    ...(record['context'] === undefined ? {} : { context: parseContext(record['context']) }),
  }

  for (const key of Object.keys(record)) {
    if (key !== 'domain' && key !== 'address' && key !== 'nonce' && key !== 'context' && key !== 'hash') {
      throw new OwnershipError(`This challenge carries an unknown field "${key}". Remove it and ask again.`)
    }
  }

  if (record['hash'] !== undefined) {
    const claimed = text(record['hash'], 'hash', 128).toUpperCase()
    if (claimed !== ownershipChallengeHash(challenge)) {
      throw new OwnershipError(
        'This challenge names a digest that is not the digest of its own fields. Refusing to sign it.',
      )
    }
  }

  return challenge
}

/**
 * Sign a challenge for the address the private key belongs to.
 *
 * `privateKey` is the caller's problem to hold; in Button it is held for one
 * call in `src/ownership.ts` and only until the SDK's own signer exists. The
 * digest signed is derived here from the parsed challenge, so what arrived on
 * the wire never becomes what gets signed.
 */
export async function signOwnershipChallenge(
  keys: { privateKey: string; address: string },
  message: OwnershipChallengeMessage,
): Promise<OwnershipProof> {
  const challenge = parseOwnershipChallenge(message)
  if (challenge.address !== keys.address) {
    throw new OwnershipError(
      `This challenge is for ${challenge.address}, and this wallet is ${keys.address}. A wallet signs only for itself.`,
    )
  }
  return {
    address: keys.address,
    signature: await signHash(keys.privateKey, ownershipChallengeHash(challenge)),
    challenge,
  }
}

/**
 * Check a proof against what the asking server expected.
 *
 * Takes an address and nothing else — no client, no node, no wallet — so a game
 * server holding no Kei key can run it. Returns `false` for everything an
 * untrusted client could send, and never puts the proof in an error. It throws
 * only when `expected` is malformed, which is the calling server's own bug.
 *
 * The nonce is consumed **after** the signature verifies, so a forged signature
 * cannot burn the nonce an honest client is still holding.
 */
export async function verifyOwnershipProof(proof: unknown, expected: OwnershipExpectation): Promise<boolean> {
  const wanted = ownershipChallengeHash(parseOwnershipChallenge(expected))

  let candidate: OwnershipProof
  try {
    const record = plainObject(proof, 'proof')
    candidate = {
      address: text(record['address'], 'address', 128),
      signature: text(record['signature'], 'signature', 256),
      challenge: parseOwnershipChallenge(record['challenge']),
    }
  } catch {
    return false
  }

  // The challenge has to be the one that was asked for, byte for byte — which
  // is what refuses a proof made for another address, another game, another
  // room, or an older nonce, all in one comparison.
  if (candidate.address !== expected.address) return false
  if (candidate.challenge.address !== candidate.address) return false
  if (ownershipChallengeHash(candidate.challenge) !== wanted) return false

  let publicKey: string
  try {
    publicKey = publicKeyFromAddress(candidate.address)
  } catch {
    return false
  }

  let signed = false
  try {
    signed = await verifyHash(wanted, candidate.signature, publicKey)
  } catch {
    return false
  }
  if (!signed) return false

  return expected.nonces ? expected.nonces.use(candidate.challenge.nonce) : true
}

// ------------------------------------------------------------------ internals

/** Absent context and empty context hash identically, so two sides can differ. */
function normalise(challenge: OwnershipChallenge): Record<string, unknown> {
  const context = challenge.context && Object.keys(challenge.context).length > 0 ? challenge.context : undefined
  return {
    domain: challenge.domain,
    address: challenge.address,
    nonce: challenge.nonce,
    ...(context === undefined ? {} : { context }),
  }
}

function plainObject(value: unknown, what: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new OwnershipError(`That ${what} is not an object.`)
  }
  const record = value as Record<string, unknown>
  for (const key of Object.keys(record)) {
    // An accessor could answer one thing for the check and another for the use.
    const descriptor = Object.getOwnPropertyDescriptor(record, key)
    if (descriptor && !('value' in descriptor)) {
      throw new OwnershipError(`That ${what} has a getter on "${key}". Send plain values.`)
    }
  }
  return record
}

function text(value: unknown, what: string, max: number): string {
  if (typeof value !== 'string' || value.length === 0) {
    throw new OwnershipError(`The challenge's ${what} must be a non-empty string.`)
  }
  if (value.length > max) {
    throw new OwnershipError(`The challenge's ${what} is longer than ${max} characters.`)
  }
  if (hasControlCharacter(value)) {
    throw new OwnershipError(`The challenge's ${what} contains a control character.`)
  }
  return value
}

function parseContext(value: unknown): Record<string, ChallengeContextValue> {
  const record = plainObject(value, 'challenge context')
  const keys = Object.keys(record)
  if (keys.length > MAX_CHALLENGE_CONTEXT_ENTRIES) {
    throw new OwnershipError(`A challenge context holds at most ${MAX_CHALLENGE_CONTEXT_ENTRIES} entries.`)
  }

  const context: Record<string, ChallengeContextValue> = {}
  for (const key of keys) {
    if (key.length === 0 || key.length > MAX_CHALLENGE_CONTEXT_KEY || hasControlCharacter(key)) {
      throw new OwnershipError(`"${key}" is not a usable challenge context key.`)
    }
    const entry = record[key]
    if (typeof entry === 'string') {
      if (entry.length > MAX_CHALLENGE_CONTEXT_VALUE || hasControlCharacter(entry)) {
        throw new OwnershipError(`The challenge context value at "${key}" is too long or has a control character.`)
      }
      context[key] = entry
    } else if (typeof entry === 'number') {
      if (!Number.isFinite(entry)) throw new OwnershipError(`The challenge context value at "${key}" is not finite.`)
      context[key] = entry
    } else if (typeof entry === 'boolean') {
      context[key] = entry
    } else {
      throw new OwnershipError(`The challenge context value at "${key}" must be a string, number, or boolean.`)
    }
  }
  return context
}

/** By code point, so a lone surrogate or a NEL does not slip through a regex. */
function hasControlCharacter(value: string): boolean {
  for (const character of value) {
    const point = character.codePointAt(0)!
    if (point < 0x20 || (point >= 0x7f && point <= 0x9f)) return true
  }
  return false
}
